### ISSUE TITLE
KeyError: '/Root'

### ISSUE THREAD

**Issue by jueti** [caj2pdf/caj2pdf#46] opened 2020-03-21 02:59 UTC
**Environment**

Python 3.7.6
mupdf-1.16.0-windows
pypdf2==1.26.0

**File can't convert**
[基于微观核力的有限核和中子-中子散射截面研究 - 中国知网](http://new.gb.oversea.cnki.net/KCMS/detail/detail.aspx?dbcode=CDFD&dbname=CDFDLAST2019&filename=1019873193.nh&v=MTQ1MzFGckpFYlBJUjhlWDFMdXhZUzdEaDFUM3FUcldNMUZyQ1VSN3FmWk9SdUZ5bmhWTDNOVkYyNkY3dS9IZEQ=)
<details><summary>百度云盘下载</summary>
<p>链接: https://pan.baidu.com/s/1Psn7zTK1B-tGLPZByFbh3w 提取码: caj0 复制这段内容后打开百度网盘手机App，操作更方便哦</p>
</details>

**Command**
```powershell
PS> pipenv install PyPDF2
PS> pipenv run python caj2pdf convert 1.caj -o 1.pdf                                                                    Loading .env environment variables…
Traceback (most recent call last):
  File "caj2pdf", line 41, in <module>
    caj.convert(args.output)
  File "E:\Tools\caj2pdf\cajparser.py", line 72, in convert
    self._convert_caj(dest)
  File "E:\Tools\caj2pdf\cajparser.py", line 231, in _convert_caj
    add_outlines(self.get_toc(), "pdf_toc.pdf", dest)
  File "E:\Tools\caj2pdf\utils.py", line 185, in add_outlines
    for p in pdf_in.pages:
  File "C:\Users\Jason\.virtualenvs\caj2pdf-a0e2zHHU\lib\site-packages\PyPDF2\utils.py", line 159, in __getitem__
    len_self = len(self)
  File "C:\Users\Jason\.virtualenvs\caj2pdf-a0e2zHHU\lib\site-packages\PyPDF2\utils.py", line 150, in __len__
    return self.lengthFunction()
  File "C:\Users\Jason\.virtualenvs\caj2pdf-a0e2zHHU\lib\site-packages\PyPDF2\pdf.py", line 1155, in getNumPages
    self._flatten()
  File "C:\Users\Jason\.virtualenvs\caj2pdf-a0e2zHHU\lib\site-packages\PyPDF2\pdf.py", line 1505, in _flatten
    catalog = self.trailer["/Root"].getObject()
  File "C:\Users\Jason\.virtualenvs\caj2pdf-a0e2zHHU\lib\site-packages\PyPDF2\generic.py", line 516, in __getitem__
    return dict.__getitem__(self, key).getObject()
KeyError: '/Root'
```

**Comment by HinTak** [comment] 2021-01-08 18:56
Can you zip it up and attach here? cannot use either cnki or baidu .

**Comment by lelandyang** [comment] 2021-01-09 02:36
The file is herein attached. The issue can now be closed accordingly.
[1.zip](https://github.com/caj2pdf/caj2pdf/files/5790050/1.zip)

**Comment by HinTak** [comment] 2021-01-09 12:54
Thanks; put under the CAJSamples repo now. I still see the `KeyError: '/Root'` error though. Do you not?

@lelandyang you should be able to put files under CAJSamples directly yourself. Would like at least another of the older types with JBIG2 images, and ones with C8 headers too. (have just one of either type) - and perhaps any with non-inverted jpeg's too (though I suspect the positioning issue would get fixed together when sub-page images get positioned correctly).

**Comment by lelandyang** [comment] 2021-01-09 14:52
"Do you not" seems that you are scolding me, did I do somthing wrong? 
I will commit to the sample repo once more samples available. 
Again, thank you for your work on the project.

**Comment by HinTak** [comment] 2021-01-09 16:50
Sorry, it was a simple question "do you see the reported problem not there anymore?" . You closed this issue... When a issue get closed, it is usually assumed that the problem is no longer there, or a equivalent / smaller issue is already filed elsewhere?

**Comment by lelandyang** [comment] 2021-01-10 03:28
> 
> 
> Sorry, it was a simple question "do you see the reported problem not there anymore?" . You closed this issue... When a issue get closed, it is usually assumed that the problem is no longer there, or a equivalent / smaller issue is already filed elsewhere?

What I thought was that the user provided a sample that indicates the "bug", which, according to the stack trace, is not the bug of our program, but from the upstream package PyPDF2, it is appropriate to report it to upstream repo; and we now have the sample in our sample repo, I therefore close this issue.
It is better, from my point of view, to put all issues together in one issue while closing the other.
The supplied sample is a PDF-based sample, the mechanism for the fix is to remove CAJ header and XML tag (if any), then add missing /Catalog, top level /Pages object, sometimes all /Pages object, these procedures relies on a third party package PyPDF2.  Later operation appending outline also requires the package.
Honestly speaking, this is not a rare problem, many PDF based CAJ conversion failed throwing the same error:  `KeyError: '/Root'`.
The PDF-based CAJ conversion relies greatly on mutools and PyPDF2, this leads to many weird issues such as KeyError while appending pdf outline or xref fix. Similarly, the issue https://github.com/caj2pdf/caj2pdf/issues/49 points to the package. The C rewrite version deals with low-level operation with its own code.

**Comment by HinTak** [comment] 2021-01-10 08:54
I guess I do not think it is a pypdf2 issue. Most (All?) the remaining opened issues seem to be the same type - the pdf is generated with wrong object order / number assignment / cross-reference . E. g. The one where a few pages which should be in the middle of the document, ended up at the end of the pdf. I think caj2pdf's input to pypdf2 is perhaps incorrect.

The c rewrite version have dangling references - hence the crash, which I worked-arounded. Argh, I just remembered - dangling references cause crashes only on linux, while on Solaris (and perhaps mac is x too, as in #49 ) , the os suppresses such programming mistakes, as a convenience. Dangling references is a programmers' mistake, but it is visible and causes crashes only if uninitialized memory is not zero'ed. The ANSI C or Posix standard explicitly says that you should not expect uninitialized memory to be zero'ed, but some OS vendors do it anyway, as a convenience to users. The Linux people believe that the OS should not try to hide user errors.

(many years ago I have seen a program which works "correctly" under solaris but crashes on linux, found the bug in the code with GDB and looked up what the international standard says. The standard says "we do not require it", so the Linux people don't, but the Solaris people do. Mac os x is closer to Solaris than to Linux, so likely go in that direction too.)

**Comment by HinTak** [comment] 2022-07-07 03:46
Somehow current code (+ pyPDF2 1.26.0 on my system, and mupdf 1.20.0) works perfectly now. Closing.

**Closed by HinTak** 2022-07-07 03:46 UTC
Labels: bug
